version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: next_app_prod
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      DB_HOST: mariadb
      DB_PORT: 3306
      DB_DATABASE: mydb
      DB_USER: myuser
      DB_PASSWORD: mypassword
    depends_on:
      - mariadb
    restart: unless-stopped

  mariadb:
    image: mariadb:10.11
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: unless-stopped

volumes:
  mariadb_data:
